import { isGtnhInstalled } from "@/lib/game-packs";
import { catalog } from "@/lib/db";
import { hydrateRecipeVariants } from "@/lib/recipe-data";
import { fluidLookupItems } from "@/lib/fluid-containers";
import { neiAssociatedRecipeIds } from "@/lib/nei-associated-recipes";
import type { Recipe } from "@/lib/model";
import { compareRecipeHandlers } from "@/lib/recipe-order";
import { machineTier } from "@/lib/machine-selection";
import { comparePickerRecipes, recipeTier } from "@/lib/recipe-picker-order";
export async function GET(request: Request) {
  if (!isGtnhInstalled())
    return Response.json(
      { error: "Install the GTNH game pack first." },
      { status: 409 },
    );
  const url = new URL(request.url),
    item = url.searchParams.get("item"),
    ids = url.searchParams.get("ids");
  if (!item && !ids) return Response.json([]);
  const uses = url.searchParams.get("mode") === "uses";
  const category = url.searchParams.get("mode") === "category";
  const lookupItems =
    ids || category ? [] : await fluidLookupItems(item!);
  let machineHandlers: string[] = [];
  // Start with the indexed ingredient lookup instead of testing every recipe
  // in the version catalog for a matching ingredient.
  const matchingIds = category
    ? (
        await catalog.recipe.findMany({
          where: { enabled: true, handler: item! },
          select: { id: true },
        })
      ).map((r) => r.id)
    : ids
      ? ids.split(",").slice(0, 2000)
      : (
          await catalog.ingredient.findMany({
            where: {
              itemId: { in: lookupItems },
              direction:
                url.searchParams.get("mode") === "uses" ? "input" : "output",
            },
            select: { recipeId: true },
            distinct: ["recipeId"],
          })
        ).map((i) => i.recipeId);
  if (!ids && !category) {
    matchingIds.push(...(await Promise.all(lookupItems.map(id => neiAssociatedRecipeIds(id, uses)))).flat());
  }
  if (!ids && uses) {
    const [variants, machines] = await Promise.all([
      catalog.ingredientVariant.findMany({
        where: {
          itemId: { in: lookupItems },
          ingredient: { direction: "input" },
        },
        select: { ingredient: { select: { recipeId: true } } },
      }),
      catalog.$queryRaw<{ handler: string }[]>`
        SELECT DISTINCT handler FROM Recipe
        WHERE enabled = 1 AND EXISTS (
          SELECT 1 FROM json_each(Recipe.layout, '$.machineIds')
          WHERE value = ${item!}
        )
      `,
    ]);
    machineHandlers = machines.map((machine) => machine.handler);
    matchingIds.push(...variants.map((value) => value.ingredient.recipeId));
  }
  const availabilityOnly = url.searchParams.get("availability") === "1";
  if (!matchingIds.length && !machineHandlers.length)
    return Response.json(availabilityOnly ? { exists: false } : []);
  const excludedMachineRecipes = new Set<string>();
  if (machineHandlers.length) {
    const machine = await catalog.item.findUnique({ where: { id: item! } });
    const exactTier = machine ? machineTier(machine) : undefined;
    const machineRecipes = await catalog.recipe.findMany({
      where: { enabled: true, handler: { in: machineHandlers } },
      select: { id: true, handler: true, euPerTick: true, details: true },
    });
    for (const recipe of machineRecipes) {
      if (exactTier && recipeTier(recipe) !== exactTier) excludedMachineRecipes.add(recipe.id);
      else matchingIds.push(recipe.id);
    }
  }
  const uniqueIds = [...new Set(matchingIds)].filter(id => !excludedMachineRecipes.has(id));
  if (availabilityOnly) {
    for (let start = 0; start < uniqueIds.length; start += 300) {
      const match = await catalog.recipe.findFirst({
        where: { enabled: true, id: { in: uniqueIds.slice(start, start + 300) } },
        select: { id: true },
      });
      if (match) return Response.json({ exists: true });
    }
    return Response.json({ exists: false });
  }
  const recipes: Recipe[] = [];
  // Common fluids have thousands of uses. Bound both the IN query and the
  // ingredient/item relation queries generated by Prisma to SQLite's limits.
  for (let start = 0; start < uniqueIds.length; start += 300) {
    recipes.push(
      ...(await catalog.recipe.findMany({
        where: {
          enabled: true,
          id: { in: uniqueIds.slice(start, start + 300) },
        },
        include: {
          ingredients: { orderBy: { slot: "asc" }, include: { item: true } },
        },
      })),
    );
  }
  // The browser creates tabs and selects its initial tab in response order.
  // Machine lookups prioritize supported categories, then use NEI tab priorities.
  const preferred = new Set(machineHandlers);
  recipes.sort(
    (a, b) =>
      Number(preferred.has(b.handler)) - Number(preferred.has(a.handler)) ||
      compareRecipeHandlers(a.handler, b.handler) ||
      comparePickerRecipes(a, b) ||
      (a.id < b.id ? -1 : a.id > b.id ? 1 : 0),
  );
  return Response.json(await hydrateRecipeVariants(recipes));
}
